FROM postgres:17

# Копируем файлы инициализации и конфигурации
COPY ./master-init.sh /docker-entrypoint-initdb.d/master-init.sh
COPY ./pg_hba_master.conf /var/lib/postgresql/data/pg_hba.conf
RUN mkdir -p /var/lib/postgresql/data
VOLUME /var/lib/postgresql/data

# Переменные окружения
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=test_db