FROM postgres:17

# Копируем файлы инициализации
COPY ./slave-init.sh /docker-entrypoint-initdb.d/master-init.sh
RUN mkdir -p /var/lib/postgresql/data
VOLUME /var/lib/postgresql/data

# Переменные окружения
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=test_db