---
- name: Install Elasticsearch from Yandex Mirror
  hosts: elasticsearch-server
  become: true
  vars_files:
    - "./vars/main.yml"
  tasks:

# Установка необходимых пакетов
    - name: install packages
      apt:
        name:
          - apt-transport-https
          - gnupg2
          - curl
          - default-jre-headless
          - libwww-perl
        state: present
        update_cache: yes

# Добавление репозитория из зеркала Yandex mirror
    - name: Добавление Yandex mirror в репозиторий
      apt_repository:
        repo: "deb [trusted=yes] {{ yandex_mirror_url }}"
        state: present
        filename: elasticsearch

# Установка elasticsearch из добавленного репозитория
    - name: Установка Elasticsearch
      apt:
        name: elasticsearch
        state: present
        update_cache: yes

    - name: Copy Elasticsearch config file
      copy:
        src: ./configs/elasticsearch/config.yml
        dest: /etc/elasticsearch/elasticsearch.yml

# Включение и запуск elasticsearch
    - name: Включение и запуск Elasticsearch
      systemd:
        name: elasticsearch
        enabled: yes
        state: started
        daemon_reload: yes