[all:vars]
ansible_user=vitas
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q vitas@111.88.246.31"'

application-load-balancer=81.26.178.14:80

bastion=111.88.246.31
  
web-a=10.0.1.15
web-b=10.0.2.34

elasticsearch-server=10.0.1.21

zabbix-server=111.88.250.251

kibana-server=111.88.242.201


[bastion]
bastion-server ansible_host=bastion.ru-central1.internal

[elasticsearch]
elasticsearch-server ansible_host=elasticsearch-server.ru-central1.internal

[kibana]
kibana-server ansible_host=kibana-server.ru-central1.internal

[hosts]
web-a ansible_host=web-a.ru-central1.internal
web-b ansible_host=web-b.ru-central1.internal
  
[monitoring]
zabbix-server ansible_host=zabbix-server.ru-central1.internal
