---
- name: install nginx
  hosts: web-b
  become: yes
  vars_files:
    - "./vars/main.yml"

  tasks:
  - name: install nginx
    apt:
      name:
       - nginx
      state: present
      update_cache: yes

  - name: copy index.nginx-debian.html web-b
    copy:
      src: ./web-b_index/index.nginx-debian.html
      dest: /var/www/html/index.nginx-debian.html
      remote_src: no
      force: yes
      backup: yes

  - name: reload nginx web-b
    service:
      name: nginx
      state: reloaded