---
- name: install zabbix-server
  hosts: zabbix-server
  become: true
#  gather_facts: true
#  vars:
#    ansible_ssh_user: vitas
  vars_files:
    - "./vars/main.yml"
  
  tasks:

# Сначала устанавливаю postgresql, apache2
  - name: install postgresql, apache2
    apt:
      name:
       - postgresql
       - apache2
      state: present
      update_cache: yes

# Скачиванию .deb пакет конфигурации репозитория с официального сайта Zabbix 
  - name: Download Zabbix repository .deb package
    get_url:
      url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
      dest: /tmp/zabbix-release_latest_7.0+ubuntu22.04_all.deb
      mode: '0644'

#      url: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.4-0.1+ubuntu22.04_all.deb
#      dest: /tmp/zabbix-release_latest.deb

# Устанавливаю его с помощью apt
  - name: Install Zabbix repository
    remote_user: vitas
    apt:
      deb: /tmp/zabbix-release_latest_7.0+ubuntu22.04_all.deb
      update_cache: yes

#      deb: /tmp/zabbix-release_latest.deb

# Установка компонентов
  - name: Install components zabbix-server, frontend, zabbix-agent
    apt:
      name:
        - zabbix-server-pgsql 
        - zabbix-frontend-php 
        - php8.1-pgsql 
        - zabbix-apache-conf 
        - zabbix-sql-scripts 
        - zabbix-agent
      state: present
      update_cache: yes

  - name: restart services
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
    loop:
      - zabbix-server
      - zabbix-agent
      - postgresql
      - apache2

# Создаю пользователя zabbix с паролем для postgresql
  - name: Create db_user for postgresql_db with password
    ansible.builtin.shell: |
      su - postgres -c 'psql --command "CREATE USER {{ zabbix_db_user }} WITH PASSWORD '\'{{ zabbix_db_password }}\'';"'

# Создаю БД zabbix для пользователя zabbix
  - name: Create postgresql_db for db_user
    ansible.builtin.shell: |
      su - postgres -c 'psql --command "CREATE DATABASE {{ zabbix_db_name }} OWNER {{ zabbix_db_user }};"'

# Импортирую первоначальную схему и данные 
  - name: Import schema
    ansible.builtin.shell: |
      zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u {{ zabbix_db_user }} psql {{ zabbix_db_name }}

# Прописываю пароль для БД в zabbix_server.conf
  - name: Set DBPassword in Zabbix config
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '# DBPassword='
      line: 'DBPassword={{ zabbix_db_password }}'

# Перезагрузка и запуск по умолчанию служб
  - name: Enable and restart services
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
      state: restarted
    loop:
      - zabbix-server
      - zabbix-agent
      - apache2

#---------------------------- до этого места все работает!!!









#- name: Создание пользователя PostgreSQL
#  community.general.postgresql_user:
#    state: present
#    name: "{{ db_user }}"
#    password: "{{ db_password }}"
#    role_attr_flags: "CREATEDB"
#  become_user: postgres

#- name: Create db user
#  community.postgresql.postgresql_user:
#    state: present
#    name: "{{ db_user }}"
#    password: "{{ db_password }}"


#- name: Создать пользователя базы данных
#  become_user: postgres
#  become_method: sudo
#  community.postgresql.postgresql_user:
#    name: dbuser
#    password: password
#    state: present
#    role_attr_flags: "CREATEDB"