#cloud-config
users:
  - name: vitren
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICYQ5sEmwilsTBwf13m2AXDtyoi7XF/EUa/TdN2Kcmnj vitaliyrenev@vitas
