---
- name: jenkins for jenkins-server
  gather_facts: true
  become: yes
  hosts: jenkins
  vars:
    ansible_ssh_user: vitren
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

- name: nexus for nexus-server
  gather_facts: true
  become: yes
  vars:
    ansible_ssh_user: vitren
  hosts: nexus
  roles:
     - docker

