setup.kibana:
  host: "kibana-server:5601"
#  host: "{{ kibana_server_ip }}:5601"

# Настройка вывода в Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch-server:9200"]
  # Если включена безопасность:
  # username: "elastic"
  # password: "your_password"

# Автоматическая загрузка шаблонов индексов и дашбордов
setup.dashboards.enabled: true
setup.template.settings:
  index.number_of_shards: 1

# Путь к папке с конфигами модулей
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
