FROM mysql:9.3
# Копируем файлы конфигурации
COPY ./master-2.cnf /etc/mysql/conf.d/my.cnf
COPY ./master-2.sql /docker-entrypoint-initdb.d/start.sql
# Переменные окружения для настройки репликации
ENV MYSQL_ROOT_PASSWORD=vitas2025
# Запускаем сервисы
CMD ["mysqld"]