CREATE USER 'repl_2'@'%' IDENTIFIED BY 'password';
GRANT REPLICATION SLAVE ON *.* TO 'repl_2'@'%';
CHANGE REPLICATION SOURCE TO
SOURCE_HOST='master-1',
SOURCE_USER='repl_1',
SOURCE_PASSWORD='password',
SOURCE_SSL=1;
START REPLICA;