CREATE USER 'repl_1'@'%' IDENTIFIED BY 'password';
GRANT REPLICATION SLAVE ON *.* TO 'repl_1'@'%';
CHANGE REPLICATION SOURCE TO
SOURCE_HOST='master-2',
SOURCE_USER='repl_2',
SOURCE_PASSWORD='password',
SOURCE_SSL=1;
START REPLICA;